// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/AtomicWorkspaceShowdown-DTk3nf/index.tsx": () => import("../components/mockups/templates/AtomicWorkspaceShowdown-DTk3nf/index.tsx"),
  "./components/mockups/templates/AtomicWorkspaceShowdown-OEtv9Z/index.tsx": () => import("../components/mockups/templates/AtomicWorkspaceShowdown-OEtv9Z/index.tsx")
};
